# run `skaffold fix` to convert v2alpha3 to v4beta6 (latest at the moment)
# apiVersion: skaffold/v2alpha3
# kind: Config
# deploy:
#   kubectl:
#     manifests:
#       - ./infra/k8s/*
# build:
#   local:
#     push: false
#   artifacts:
#     - image: srt1104/client
#       context: client
#       docker:
#         dockerfile: Dockerfile
#       sync:
#         manual:
#           - src: 'src/**/*.js'
#             dest: .
#     - image: srt1104/comments
#       context: comments
#       docker:
#         dockerfile: Dockerfile
#       sync:
#         manual:
#           - src: '*.js'
#             dest: .
#     - image: srt1104/event-bus
#       context: event-bus
#       docker:
#         dockerfile: Dockerfile
#       sync:
#         manual:
#           - src: '*.js'
#             dest: .
#     - image: srt1104/moderation
#       context: moderation
#       docker:
#         dockerfile: Dockerfile
#       sync:
#         manual:
#           - src: '*.js'
#             dest: .
#     - image: srt1104/posts
#       context: posts
#       docker:
#         dockerfile: Dockerfile
#       sync:
#         manual:
#           - src: '*.js'
#             dest: .
#     - image: srt1104/query
#       context: query
#       docker:
#         dockerfile: Dockerfile
#       sync:
#         manual:
#           - src: '*.js'
#             dest: .

apiVersion: skaffold/v4beta6
kind: Config
build:
  artifacts:
    - image: srt1104/client
      context: client
      sync:
        manual:
          - src: src/**/*.js
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: srt1104/comments
      context: comments
      sync:
        manual:
          - src: '*.js'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: srt1104/event-bus
      context: event-bus
      sync:
        manual:
          - src: '*.js'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: srt1104/moderation
      context: moderation
      sync:
        manual:
          - src: '*.js'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: srt1104/posts
      context: posts
      sync:
        manual:
          - src: '*.js'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: srt1104/query
      context: query
      sync:
        manual:
          - src: '*.js'
            dest: .
      docker:
        dockerfile: Dockerfile
  local:
    push: false
manifests:
  rawYaml:
    - ./infra/k8s/*
deploy:
  kubectl: {}